### ISSUE TITLE
Add types to DefinatelyTyped

### ISSUE THREAD

**Issue by gbaranski** [polkadot-js/ts#114]
What do you think about publishing types to [DefinatelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)? Importing types from this repo is quite problematic.

**Comment by jacogr** [comment]
As mentioned in the README - "TypeScript definitions for packages that are not (yet) available on DefinitelyTyped" - that is always preferable.

So if it can be some use and somebody can take it what is here and get it acceptable in DT, all good and it is the perfect outcome. I just don't have the capacity to deal with yet more repos so it is not something I can pursue.

**Comment by gbaranski** [comment]
Do You have any project that is using libp2p and types from this repository? For me those types sometimes work and sometimes they don't. Also I'm not possible to link types to my project for some reason, they just don't get detected.

**Comment by jacogr** [comment]
Yes. The client repo uses them - and other non-libp2p types in here are used in the other repos in this org as well. 

(That client has not gotten any attention this year at all... not enough hours)

**Comment by gbaranski** [comment]
Okay I'll continue work on libp2p types here https://github.com/gbaranski/DefinitelyTyped

**Comment by jacogr** [comment]
Excellent. Will keep an eye :)
